
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'rightEQUALSleftPLUSMINUSleftPORDIVIDEDIVIDE EQUALS LPAR MINUS NUMBER PLUS POR RPAR VARexpr : NUMBERexpr : VARexpr : VAR EQUALS exprexpr : expr PLUS exprexpr : expr MINUS exprexpr : expr POR exprexpr : expr DIVIDE exprexpr : LPAR expr RPARexpr : MINUS expr'
    
_lr_action_items = {'NUMBER':([0,4,5,6,7,8,9,10,],[2,2,2,2,2,2,2,2,]),'VAR':([0,4,5,6,7,8,9,10,],[3,3,3,3,3,3,3,3,]),'LPAR':([0,4,5,6,7,8,9,10,],[5,5,5,5,5,5,5,5,]),'MINUS':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,],[4,7,-1,-2,4,4,4,4,4,4,4,-9,7,-4,-5,-6,-7,7,-8,]),'$end':([1,2,3,11,13,14,15,16,17,18,],[0,-1,-2,-9,-4,-5,-6,-7,-3,-8,]),'PLUS':([1,2,3,11,12,13,14,15,16,17,18,],[6,-1,-2,-9,6,-4,-5,-6,-7,6,-8,]),'POR':([1,2,3,11,12,13,14,15,16,17,18,],[8,-1,-2,8,8,8,8,-6,-7,8,-8,]),'DIVIDE':([1,2,3,11,12,13,14,15,16,17,18,],[9,-1,-2,9,9,9,9,-6,-7,9,-8,]),'RPAR':([2,3,11,12,13,14,15,16,17,18,],[-1,-2,-9,18,-4,-5,-6,-7,-3,-8,]),'EQUALS':([3,],[10,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expr':([0,4,5,6,7,8,9,10,],[1,11,12,13,14,15,16,17,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expr","S'",1,None,None,None),
  ('expr -> NUMBER','expr',1,'p_num','hoc2.py',17),
  ('expr -> VAR','expr',1,'p_var','hoc2.py',21),
  ('expr -> VAR EQUALS expr','expr',3,'p_var_equals_exp','hoc2.py',25),
  ('expr -> expr PLUS expr','expr',3,'p_exp_plus_exp','hoc2.py',30),
  ('expr -> expr MINUS expr','expr',3,'p_exp_min_exp','hoc2.py',34),
  ('expr -> expr POR expr','expr',3,'p_exp_por_exp','hoc2.py',38),
  ('expr -> expr DIVIDE expr','expr',3,'p_exp_div_exp','hoc2.py',42),
  ('expr -> LPAR expr RPAR','expr',3,'p_par_exp_par','hoc2.py',49),
  ('expr -> MINUS expr','expr',2,'p_min_exp','hoc2.py',53),
]
